### ISSUE TITLE
Epic: User Front End

### ISSUE THREAD

**Issue by harveychurch** [Northill/TuneTrack#3]
This is an epic for all the user front end:

- [x] #1 Create Login Screen
- [x] #5 A way to view uploaded songs
- [x] #14 New User Creation
- [x] #22 Implement React Router
- [x] #23 A way to view specific songs
